[plotly-base-artifacts]
git-tree-sha1 = "23a2952b9c777216235209bc7e40d3485a5288ff"

    [[plotly-base-artifacts.download]]
    sha256 = "e4974519a4e9fc1906b354865eba2fe5afaf77dbb4dc27fd8b518f621ff543ac"
    url = "https://github.com/halleysfifthinc/PlotlyBase.jl/releases/download/plotly-base-artifacts-2.31.1/plotly-base-artifacts-2.31.1.tar.gz"
